config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'menu#search'
  resources :catagories
  get 'menu', to: 'menu#index'
  devise_for :users
  resources :products
  root 'pages#home'
  get 'catering', to: 'pages#catering'
  get 'info', to: 'pages#info'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catagory.rb
class Catagory < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
  before_action :set_catagory, only: [:show, :edit, :update, :destroy]

  # GET /catagories
  # GET /catagories.json
  def index
    @catagories = Catagory.all
  end

  # GET /catagories/1
  # GET /catagories/1.json
  def show
  end

  # GET /catagories/new
  def new
    @catagory = Catagory.new
  end

  # GET /catagories/1/edit
  def edit
  end

  # POST /catagories
  # POST /catagories.json
  def create
    @catagory = Catagory.new(catagory_params)

    respond_to do |format|
      if @catagory.save
        format.html { redirect_to @catagory, notice: 'Catagory was successfully created.' }
        format.json { render :show, status: :created, location: @catagory }
      else
        format.html { render :new }
        format.json { render json: @catagory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catagories/1
  # PATCH/PUT /catagories/1.json
  def update
    respond_to do |format|
      if @catagory.update(catagory_params)
        format.html { redirect_to @catagory, notice: 'Catagory was successfully updated.' }
        format.json { render :show, status: :ok, location: @catagory }
      else
        format.html { render :edit }
        format.json { render json: @catagory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catagories/1
  # DELETE /catagories/1.json
  def destroy
    @catagory.destroy
    respond_to do |format|
      format.html { redirect_to catagories_url, notice: 'Catagory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catagory
      @catagory = Catagory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def catagory_params
      params.require(:catagory).permit(:heading, :body, :display)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :set_cats
  def index
    @page = 'menu'
    @products = Product.all
  end

  def search
    query = params[:search]

    results = Product.where('name LIKE ?', "%#{query}%")
    if params[:filter] == 'Select Filter'
      @products = results
    else
      # 'Dairy Free' -> 'Dairy_Free' -> 'dairy_free' -> :dairy_free
      symbol = params[:filter].gsub(/ /, '_').downcase!.to_sym
      # @products = results.where(:dairy_free => true)
      @products = results.where(symbol => true)
    end
  end

  private

  def set_cats
    @cats = Catagory.all.where(display: true)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page = 'home'
  end

  def catering
    @page = 'catering'
  end

  def info
    @page = 'info'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.category = Category.find(params[:product][:category_id])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :catagory_id, :dairy_free, :kosher, :peanut_free, :vegan, :vegetarian, :available, :catering, :featured)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/catagories/_form.html.erb
<%= simple_form_for(@catagory) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :heading %>
    <%= f.input :body %>
    <%= f.input :display %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/catagories/edit.html.erb
<h1>Editing Catagory</h1>

<%= render 'form', catagory: @catagory %>

<%= link_to 'Show', @catagory %> |
<%= link_to 'Back', catagories_path %>

app/views/catagories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Catagories</h1>

<table>
  <thead>
    <tr>
      <th>Heading</th>
      <th>Body</th>
      <th>Display</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @catagories.each do |catagory| %>
      <tr>
        <td><%= catagory.heading %></td>
        <td><%= catagory.body %></td>
        <td><%= catagory.display %></td>
        <td><%= link_to 'Show', catagory %></td>
        <td><%= link_to 'Edit', edit_catagory_path(catagory) %></td>
        <td><%= link_to 'Destroy', catagory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Catagory', new_catagory_path %>

app/views/catagories/new.html.erb
<h1>New Catagory</h1>

<%= render 'form', catagory: @catagory %>

<%= link_to 'Back', catagories_path %>

app/views/catagories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Heading:</strong>
  <%= @catagory.heading %>
</p>

<p>
  <strong>Body:</strong>
  <%= @catagory.body %>
</p>

<p>
  <strong>Display:</strong>
  <%= @catagory.display %>
</p>

<%= link_to 'Edit', edit_catagory_path(@catagory) %> |
<%= link_to 'Back', catagories_path %>

app/views/layouts/_links.html.erb
<div class="col-2">
    <h5 class="link-container">
        <%= link_to "Home", root_path, class: "link #{@page == 'home' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Menu", menu_path, class: "link #{@page == 'menu' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "catering", catering_path, class: "link #{@page == 'catering' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "More Info", info_path, class: "link #{@page == 'info' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Customer Reviews", "", class: "link #{@page == 'reviews' ? 'active' : ''}" %>
    </h5>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/_title.html.erb
<div class="title-card">
    <h1 class="title-text"> 
     Best Food 
    </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;1,800&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="<%= @page %>-page">
      <div class="row page-container">
        <%= render 'layouts/links'%>
        <div class="col-8">
          <% unless @page == "home" %>
          <% render 'layouts/title' %>
          <% end %>        
          <%= yield %>
        </div>
        <div class="col-2"></div>
      </div>
    </div>
  </body>
</html>

app/views/menu/_products.html.erb
<div class="row">
    <% @cats.each do |cat| %>
    <% if cat.products.where(featured: true).first.image.attached? %>
    <%= image_tag(cat.products.where(featured: true).first.image, class:'img-fluid')%>
    <% end %>
    <div class="col-12">
        <h1 style="text-align:center;"><%= cat.heading %></h1>
        <hr />
    </div>
    <% @products.each do |product| %>
    <% if product.category == cat %>
    <div class="col-4">
        <h5>
            <%= product.name %>
        </h5>
        <p>
            <%= product.description%>
        </p>
        <span><%= product.price %> <%= "| Available for catering" if product.catering %></span>
    </div>
    <% end %>
    <% end %>
    <% end %>
</div>

app/views/menu/index.html.erb
<div class="menu-container">
    <div class="row">
        <div class="col-12">
            <%= form_tag(search_path, method: "get", remote: true) do %>
                <div class="input-group mb-5">
                    <div class="col-8" style="padding:0">
                        <%= text_field_tag :search, '', class:'from-control', placeholder: 'Search...', onkeydown: 'clickSubmit();'%>
                    </div>
                    <div class="col-4" style="padding:0">
                        <%= select_tag "filter", options_for_select(['Select Filter',
                         'Dairy Free',
                         'Gluten Free',
                         'Kosher', 
                         'Peanut Free', 
                         'Vegan', 
                         'Vegetarian']), class:'custom-select'%>
                    </div>
                    <div class="col-1" style="padding:0">
                        <%= submit_tag "search", class:'btn btn-dark', id:'search_submit', style:'display:none'%>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <div id="menu-products-container">
        <%= render 'menu/products'%>
    </div>
</div>

<script>
    function clicksubmit(){
        $("#search_submit").trigger("click");
    }
</script>

app/views/menu/search.js.erb
$("#menu-products-container").html("<%= j render 'menu/products' %>");

app/views/pages/catering.html.erb
<h1>Pages#catering</h1>
<p>Find me in app/views/pages/catering.html.erb</p>

app/views/pages/home.html.erb
<div class="col-8"></div>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :dairy_free %>
    <%= form.check_box :dairy_free %>
  </div>

  <div class="field">
    <%= form.label :kosher %>
    <%= form.check_box :kosher %>
  </div>

  <div class="field">
    <%= form.label :peanut_free %>
    <%= form.check_box :peanut_free %>
  </div>

  <div class="field">
    <%= form.label :vegan %>
    <%= form.check_box :vegan %>
  </div>

  <div class="field">
    <%= form.label :vegetarian %>
    <%= form.check_box :vegetarian %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available %>
  </div>

  <div class="field">
    <%= form.label :catering %>
    <%= form.check_box :catering %>
  </div>

  <div class="field">
    <%= form.label :featured %>
    <%= form.check_box :featured %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Dairy free</th>
      <th>Kosher</th>
      <th>Peanut free</th>
      <th>Vegan</th>
      <th>Vegetarian</th>
      <th>Available</th>
      <th>Catering</th>
      <th>Featured</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.dairy_free %></td>
        <td><%= product.kosher %></td>
        <td><%= product.peanut_free %></td>
        <td><%= product.vegan %></td>
        <td><%= product.vegetarian %></td>
        <td><%= product.available %></td>
        <td><%= product.catering %></td>
        <td><%= product.featured %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Dairy free:</strong>
  <%= @product.dairy_free %>
</p>

<p>
  <strong>Kosher:</strong>
  <%= @product.kosher %>
</p>

<p>
  <strong>Peanut free:</strong>
  <%= @product.peanut_free %>
</p>

<p>
  <strong>Vegan:</strong>
  <%= @product.vegan %>
</p>

<p>
  <strong>Vegetarian:</strong>
  <%= @product.vegetarian %>
</p>

<p>
  <strong>Available:</strong>
  <%= @product.available %>
</p>

<p>
  <strong>Catering:</strong>
  <%= @product.catering %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @product.featured %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>